In [76]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.neighbors import KNeighborsClassifier


In [31]:
job = pd.read_csv(r"C:\Hogwarts\advanced_analytics\Datasets\JobSalary2.csv")

## Finding NA's in columns

In [32]:
job.isnull().sum()

S_No         0
Computer     2
Marketing    1
Engineer     0
dtype: int64

In [33]:
job.head()

S_No  Computer  Marketing  Engineer
0     1      84.0       55.0        75
1     2      90.0       53.0        70
2     3      63.0        NaN        88
3     4       NaN       50.0        77
4     5      63.0       41.0        89

## Dropping the rows with NA values


In [34]:
job.dropna()

S_No  Computer  Marketing  Engineer
0     1      84.0       55.0        75
1     2      90.0       53.0        70
4     5      63.0       41.0        89
5     6      75.0       54.0        85
7     8      77.0       64.0       105

## Constant imputer

In [35]:
imp = SimpleImputer(strategy = 'constant', fill_value = 50)
imp.fit_transform(job)

array([[  1.,  84.,  55.,  75.],
       [  2.,  90.,  53.,  70.],
       [  3.,  63.,  50.,  88.],
       [  4.,  50.,  50.,  77.],
       [  5.,  63.,  41.,  89.],
       [  6.,  75.,  54.,  85.],
       [  7.,  50.,  51.,  96.],
       [  8.,  77.,  64., 105.]])

In [36]:
job.mean()

S_No          4.500000
Computer     75.333333
Marketing    52.571429
Engineer     85.625000
dtype: float64

## Mean Imputer

In [37]:
imp = SimpleImputer(strategy = 'mean')
imp.fit_transform(job)

array([[  1.        ,  84.        ,  55.        ,  75.        ],
       [  2.        ,  90.        ,  53.        ,  70.        ],
       [  3.        ,  63.        ,  52.57142857,  88.        ],
       [  4.        ,  75.33333333,  50.        ,  77.        ],
       [  5.        ,  63.        ,  41.        ,  89.        ],
       [  6.        ,  75.        ,  54.        ,  85.        ],
       [  7.        ,  75.33333333,  51.        ,  96.        ],
       [  8.        ,  77.        ,  64.        , 105.        ]])

In [38]:
np_imp = SimpleImputer(strategy = 'median')
np_imp.fit_transform(job)

array([[  1.,  84.,  55.,  75.],
       [  2.,  90.,  53.,  70.],
       [  3.,  63.,  53.,  88.],
       [  4.,  76.,  50.,  77.],
       [  5.,  63.,  41.,  89.],
       [  6.,  75.,  54.,  85.],
       [  7.,  76.,  51.,  96.],
       [  8.,  77.,  64., 105.]])

In [39]:
job

S_No  Computer  Marketing  Engineer
0     1      84.0       55.0        75
1     2      90.0       53.0        70
2     3      63.0        NaN        88
3     4       NaN       50.0        77
4     5      63.0       41.0        89
5     6      75.0       54.0        85
6     7       NaN       51.0        96
7     8      77.0       64.0       105

In [102]:
pd_imp = pd.DataFrame(np_imp, columns=job.columns)

ValueError: DataFrame constructor not properly called!

# Chemical Process

In [48]:
chemdata = pd.read_csv(r"C:\Hogwarts\advanced_analytics\Datasets\ChemicalProcess.csv")

### Finding NA's in columns

In [54]:
chemdata.isnull().sum()

Yield                      0
BiologicalMaterial01       0
BiologicalMaterial02       0
BiologicalMaterial03       0
BiologicalMaterial04       0
BiologicalMaterial05       0
BiologicalMaterial06       0
BiologicalMaterial07       0
BiologicalMaterial08       0
BiologicalMaterial09       0
BiologicalMaterial10       0
BiologicalMaterial11       0
BiologicalMaterial12       0
ManufacturingProcess01     1
ManufacturingProcess02     3
ManufacturingProcess03    15
ManufacturingProcess04     1
ManufacturingProcess05     1
ManufacturingProcess06     2
ManufacturingProcess07     1
ManufacturingProcess08     1
ManufacturingProcess09     0
ManufacturingProcess10     9
ManufacturingProcess11    10
ManufacturingProcess12     1
ManufacturingProcess13     0
ManufacturingProcess14     1
ManufacturingProcess15     0
ManufacturingProcess16     0
ManufacturingProcess17     0
ManufacturingProcess18     0
ManufacturingProcess19     0
ManufacturingProcess20     0
ManufacturingProcess21     0
ManufacturingP

In [84]:
X = chemdata.drop('Yield', axis = 1)
y= chemdata['Yield']

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2022,
                                                   train_size = 0.7)

In [86]:
imp = SimpleImputer(strategy = 'mean')
imp.fit_transform(chemdata)

array([[38.  ,  6.25, 49.58, ...,  3.  ,  1.8 ,  2.4 ],
       [42.44,  8.01, 60.97, ...,  0.9 ,  1.9 ,  2.2 ],
       [42.03,  8.01, 60.97, ...,  1.  ,  1.8 ,  2.3 ],
       ...,
       [42.23,  7.5 , 58.41, ...,  0.6 ,  0.  ,  0.  ],
       [38.48,  7.53, 58.36, ...,  0.5 ,  0.  ,  0.  ],
       [39.49,  7.53, 58.36, ...,  0.6 ,  0.  ,  0.  ]])

In [87]:
imp = SimpleImputer(strategy = 'mean')
X_trn_trf = imp.fit_transform(X_train)
X_tst_trf = imp.transform(X_test)


In [91]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [92]:
lr = LinearRegression()

In [93]:
lr.fit(X_trn_trf, y_train)

LinearRegression()

In [94]:
y_pred = lr.predict(X_tst_trf)
print(r2_score(y_test, y_pred))

-1.290665707638071


### K-NN

In [97]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import KFold, GridSearchCV

In [107]:
# grid search using r2_score in mean
imp = SimpleImputer(strategy = 'mean')
scaler = StandardScaler()
knn = KNeighborsRegressor()
pipe = Pipeline([('IMPUTE', imp),('STD', scaler),('KNN', knn)])
kfold = KFold(n_splits = 5, shuffle = True, random_state= 2022)
params = {'KNN__n_neighbors': np.arange(1,11)}
knn = KNeighborsRegressor()
gcv = GridSearchCV(pipe, param_grid = params, scoring = 'r2', cv = kfold)
gcv.fit(X,y)
print(gcv.best_params_)
print(gcv.best_score_)

{'KNN__n_neighbors': 3}
0.5084559843611244


In [104]:
# grid search using r2_score in median
imp = SimpleImputer(strategy = 'median')
scaler = StandardScaler()
knn = KNeighborsRegressor()
pipe = Pipeline([('IMPUTE', imp),('STD', scaler),('KNN', knn)])
kfold = KFold(n_splits = 5, shuffle = True, random_state= 2022)
params = {'KNN__n_neighbors': np.arange(1,11)}
knn = KNeighborsRegressor()
gcv = GridSearchCV(pipe, param_grid = params, scoring = 'r2', cv = kfold)
gcv.fit(X,y)
print(gcv.best_params_)
print(gcv.best_score_)

{'KNN__n_neighbors': 3}
0.4917082485662613


In [109]:
imp = SimpleImputer()
scaler = StandardScaler()
knn = KNeighborsRegressor()
pipe = Pipeline([('IMPUTE', imp),('STD', scaler),('KNN', knn)])
print(pipe.get_params())
kfold = KFold(n_splits = 5, shuffle = True, random_state= 2022)
params = {'IMPUTE__strategy':['mean', 'median'],
          'KNN__n_neighbors': np.arange(1,11)}
gcv = GridSearchCV(pipe, param_grid = params, scoring = 'r2', cv = kfold)
gcv.fit(X,y)
print(gcv.best_params_)
print(gcv.best_score_)
# here the biggest value o/p will be displayed.(i.e mean has the highest value than median)

{'memory': None, 'steps': [('IMPUTE', SimpleImputer()), ('STD', StandardScaler()), ('KNN', KNeighborsRegressor())], 'verbose': False, 'IMPUTE': SimpleImputer(), 'STD': StandardScaler(), 'KNN': KNeighborsRegressor(), 'IMPUTE__add_indicator': False, 'IMPUTE__copy': True, 'IMPUTE__fill_value': None, 'IMPUTE__missing_values': nan, 'IMPUTE__strategy': 'mean', 'IMPUTE__verbose': 0, 'STD__copy': True, 'STD__with_mean': True, 'STD__with_std': True, 'KNN__algorithm': 'auto', 'KNN__leaf_size': 30, 'KNN__metric': 'minkowski', 'KNN__metric_params': None, 'KNN__n_jobs': None, 'KNN__n_neighbors': 5, 'KNN__p': 2, 'KNN__weights': 'uniform'}
{'IMPUTE__strategy': 'mean', 'KNN__n_neighbors': 3}
0.5084559843611244
